{{- $cronName := printf "%s" .Release.Name -}}
{{- range .Values.crons }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronName }}-{{ .name }}
  labels:
    {{- include "helm-frankenphp.labels" $ | nindent 4 }}
spec:
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: {{ (default .successfulJobsHistoryLimit 1) }}
  failedJobsHistoryLimit: {{ (default .failedJobsHistoryLimit 3) }}
  {{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ (default .backoffLimit 0) }}
      template:
        spec:
          {{- with $.Values.image.pullSecrets | default (list)}}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $.Values.serviceAccount }}
          serviceAccountName: {{ include "helm-frankenphp.serviceAccountName" $ }}
          {{- end }}
          {{- with $.Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ (default .restartPolicy "Never") }}
          containers:
            - name: {{ $cronName | lower }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy | default "IfNotPresent" }}
              {{- with $.Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              command:
                - "/bin/sh"
                - "-c"
                - {{ .command }};
              {{- with $.Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $.Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if or $.Values.php.ini $.Values.volumeMounts }}
              volumeMounts:
                {{- if $.Values.php.ini }}
                - name: php-ini
                  mountPath: /usr/local/etc/php/conf.d/99-custom.ini
                  subPath: php.ini
                {{- end }}
                {{- with $.Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- end }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $.Values.php.ini $.Values.volumes }}
          volumes:
            {{- if $.Values.php.ini }}
            - name: php-ini
              configMap:
                name: {{ $.Release.Name }}-php-ini
            {{- end }}
            {{- with $.Values.volumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
{{- end }}
