{{- $cronName := printf "%s-%s" .Release.Name "cron" -}}
{{- $context := . }}

{{- range .Values.crons }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronName }}-{{ .name }}
spec:
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ $cronName }}
              image: "{{ $.Values.api.docker.image }}:{{ $.Values.api.docker.tag }}"
              imagePullPolicy: {{ $.Values.api.docker.pullPolicy }}
              command:
                - "/bin/sh"
                - "-c"
                - {{ .command }};
              resources:
                requests:
                  cpu: {{ $.Values.api.resources.requests.cpu }}
                  memory: {{ $.Values.api.resources.requests.memory }}
                limits:
                  memory: {{ $.Values.api.resources.limits.memory }}
              {{- (include "app.sharedEnv" $) | nindent 14 }}
{{- end }}
