{{- $cronName := printf "%s" .Release.Name -}}
{{- $context := . }}
{{- range .Values.crons }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronName }}-{{ .name }}
spec:
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: {{ (default .successfulJobsHistoryLimit 1) }}
  failedJobsHistoryLimit: {{ (default .failedJobsHistoryLimit 3) }}
  {{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ (default .backoffLimit 0) }}
      template:
        spec:
          serviceAccountName: {{ include "helm-frankenphp.serviceAccountName" $context }}
          restartPolicy: {{ (default .restartPolicy "Never") }}
          containers:
            - name: {{ $cronName | lower }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ (default .imagePullPolicy "IfNotPresent") }}
              command:
                - "/bin/sh"
                - "-c"
                - {{ .command }};
              {{- if $.Values.resources }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              {{- end }}
              {{- with $.Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if $.Values.php.ini }}
              volumeMounts:
                - name: php-ini
                  mountPath: /usr/local/etc/php/conf.d/99-custom.ini
                  subPath: php.ini
              {{- with $.Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- else }}
              {{- with $.Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- end }}
          {{- if $.Values.php.ini }}
          volumes:
            - name: php-ini
              configMap:
                name: {{ $.Release.Name }}-php-ini
          {{- with $.Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          {{- with $.Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
{{- end }}
