{{- if .Values.deployment }}
{{- $name := printf "%s" .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "helm-frankenphp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "helm-frankenphp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-frankenphp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets | default (list)}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ include "helm-frankenphp.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - containerPort: 2019
              protocol: TCP
              name: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.caddyfile }}
            - name: caddyfile
              mountPath: /etc/frankenphp
          {{- end }}
          {{- if .Values.php.ini }}
            - name: php-ini
              mountPath: /usr/local/etc/php/conf.d/99-custom.ini
              subPath: php.ini
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.caddyfile }}
        - name: caddyfile # To access this volume, this name must be used inside volumeMounts of the container
          configMap:
            name: {{ .Release.Name}}-caddyfile # Name of the configMap
            items:
              - key: Caddyfile  # Name of the item we had used inside our ConfigMap (under data:)
                path: Caddyfile
      {{- end }}
      {{- if .Values.php.ini }}
        - name: php-ini
          configMap:
            name: {{ .Release.Name }}-php-ini
      {{- end }}
{{- end }}
