{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-frankenphp.fullname" . }}
  labels:
    {{- include "helm-frankenphp.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 2019
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "helm-frankenphp.selectorLabels" . | nindent 4 }}
{{- end }}
