{{- $context := . }}
{{- range .Values.consumers }}
{{- $workerName := printf "%s-%s-%s" $.Release.Name "worker" .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $workerName }}
spec:
{{- if not .autoscale }}
  replicas: {{ .replicas | default 1 }}
{{- end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ $workerName }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $workerName }}
    spec:
      {{- with $.Values.serviceAccount }}
      serviceAccountName: {{ include "helm-frankenphp.serviceAccountName" $context }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ $workerName }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "touch /tmp/kill_me" ]
          {{- with $.Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          command: # todo: find a better way to handle this
            - "/bin/sh"
            - "-c"
            - {{ .command | quote }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- if $.Values.php.ini }}
          volumeMounts:
            - name: php-ini
              mountPath: /usr/local/etc/php/conf.d/99-custom.ini
              subPath: php.ini
          {{- with $.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $.Values.php.ini }}
      volumes:
        - name: php-ini
          configMap:
            name: {{ $.Release.Name }}-php-ini
      {{- with $.Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
